included:
  - ToDoApp
excluded:
  - ToDoApp/Models/Network/
identifier_name:
  min_length:
    warning: 0
    error: 0
disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  - colon
  - comma
  - control_statement
